# 
# lib/itly/version.rb
# 
# This file is auto-generated by Iteratively.
# To update run 'itly pull analytics_service'
# 
# Questions? We're here to help:
# https://www.iterative.ly/docs/interacting-with-the-sdk/#ruby
# 

module Itly
  VERSION = "0.1.0"
end
