# 
# itly.gemspec
# 
# This file is auto-generated by Iteratively.
# To update run 'itly pull analytics_service'
# 
# Questions? We're here to help:
# https://www.iterative.ly/docs/interacting-with-the-sdk/#ruby
# 


lib = File.expand_path("../lib", __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require "itly/version"

Gem::Specification.new do |spec|
  spec.name          = "itly"
  spec.version       = Itly::VERSION
  spec.authors       = ["Iteratively Inc"]
  spec.email         = ["support@iterative.ly"]

  spec.summary       = %q{Itly SDK for Ruby.}
  spec.description   = %q{gem install itly --local. require 'itly'. itly.load(). itly.user_signed_in().}
  spec.homepage      = "https://www.iterative.ly"
  spec.license       = "MIT"

  # Prevent pushing this gem to RubyGems.org. To allow pushes either set the 'allowed_push_host'
  # to allow pushing to a single host or delete this section to allow pushing to any host.
  if spec.respond_to?(:metadata)
    spec.metadata["allowed_push_host"] = "https://iterative.ly"

    spec.metadata["homepage_uri"] = spec.homepage
    spec.metadata["source_code_uri"] = "https://iterative.ly"
    spec.metadata["changelog_uri"] = "https://iterative.ly"
  else
    raise "RubyGems 2.0 or newer is required to protect against " \
      "public gem pushes."
  end

  # Specify which files should be added to the gem when it is released.
  # The `git ls-files -z` loads the files in the RubyGem that have been added into git.
  spec.files         = Dir.chdir(File.expand_path('..', __FILE__)) do
    `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) }
  end
  spec.bindir        = "exe"
  spec.executables   = spec.files.grep(%r{^exe/}) { |f| File.basename(f) }
  spec.require_paths = ["lib"]

  spec.add_development_dependency "bundler", "~> 1.17"
  spec.add_development_dependency "rake", "~> 10.0"

  # For Segment
  spec.add_runtime_dependency "simple_segment", "~>0.3.0"
  # For validation
  spec.add_runtime_dependency "json_schemer", "~>0.2.10"
end
